# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6f5b7fef92a5228d7d05f19a359cd0cb13904eebf96197c6417c1b4b05106fc5073a95ab95f80154d3c54e3b2b4d711266c7ae139b82133bd9e1a7ec5232904

test:
  secret_key_base: 9d3902a2664e6f86829112c6c17b9b1e93f2b93e7842ef30588e8447ee3f16c2fe4d76a6f4178dc67335e0cd35cd008cd96cd43ff30fb66713037cd794564ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
